version: '2'

services:

# No need to build this for now until this is an API
#  ml_search:
#    build: .
#    volumes:
#      - .:/code
#      - ./logs:/var/log/ml_search
#    environment:
#      - LOG_LEVEL=INFO
#      - LOG_DIR=/var/log/ml_search
#      - LOG_FILE_NAME=ml_search.log
#      - ES_USE_SSL=False
#      - ES_HOST=elasticsearch:9200
#      - ES_INDEX=collection-rules
#      - ES_DOC_TYPE=document
#    restart: "on-failure:3"

  elasticsearch:
    image: elasticsearch:6.5.4
    ports:
      - "9200:9200"

  kopf:
    image: lmenezes/elasticsearch-kopf
    ports:
      - 8080:80
    environment:
      - KOPF_SERVER_NAME=dockerhost
      - KOPF_ES_SERVERS=elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:6.5.4
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./dockerfiles/ml_search_logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./dockerfiles/logs-template.json:/etc/logstash/templates/logs-template.json
      - ./logs:/var/log/ml_search
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:6.5.4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch